version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "w$@Xr606Ez]."
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - backend

  redis:
    image: redis:latest
    container_name: redis_server
    ports:
      - "6379:6379"
    networks:
      - backend

networks:
  backend:
    driver: bridge
